import { Link } from 'react-router'

export default function Liturgias() {
  return (<div>
    {/* NEXT_LINK */}
    <Link className="" to="/liturgia/010426-uma-igreja-moldada-a-imagem-de-cristo">Uma igreja moldada a imagem de Cristo - 04 de Janeiro de 2026</Link> <a className="" href="/liturgia/010426-uma-igreja-moldada-a-imagem-de-cristo/download">Download</a><br/>
    <Link className="" to="/liturgia/122825-gratidao-a-deus-por-uma-igreja-missionaria">Gratidão a Deus por uma igreja missionária - 28 de Dezembro de 2025</Link> <a className="" href="/liturgia/122825-gratidao-a-deus-por-uma-igreja-missionaria/download">Download</a><br/>
    <Link className="" to="/liturgia/122125-natal-a-mensagem-de-redencao-para-os-filhos-de-deus">Natal, A Mensagem de Redenção para os Filhos de Deus - 21 de Dezembro de 2025</Link> <a className="" href="/liturgia/122125-natal-a-mensagem-de-redencao-para-os-filhos-de-deus/download">Download</a><br/>
    <Link className="" to="/liturgia/121425-natal-a-luz-do-cristo-ressuscitado">Natal à Luz do Cristo Ressuscitado - 14 de Dezembro de 2025</Link> <a className="" href="/liturgia/121425-natal-a-luz-do-cristo-ressuscitado/download">Download</a><br/>
    <Link className="" to="/liturgia/120725-jesus-nasceu-em-seu-coracao">Jesus nasceu em seu coração? - 7 de Dezembro de 2025</Link> <a className="" href="/liturgia/120725-jesus-nasceu-em-seu-coracao/download">Download</a><br/>
    <Link className="" to="/liturgia/113025-uma-igreja-que-honra-seu-proximo">Uma igreja que honra seu próximo - 30 de Novembro de 2025</Link> <a className="" href="/liturgia/113025-uma-igreja-que-honra-seu-proximo/download">Download</a><br/>
    <Link className="" to="/liturgia/112325-uma-igreja-madura-em-cristo">Uma igreja madura em Cristo - 23 de Novembro de 2025</Link> <a className="" href="/liturgia/112325-uma-igreja-madura-em-cristo/download">Download</a><br/>
    <Link className="" to="/liturgia/111625-uma-igreja-vitoriosa">Uma igreja vitoriosa - 16 de Novembro de 2025</Link> <a className="" href="/liturgia/111625-uma-igreja-vitoriosa/download">Download</a><br/>
    <Link className="" to="/liturgia/110925-o-deus-de-toda-sabedoria">O Deus de toda sabedoria - 09 de Novembro de 2025</Link> <a className="" href="/liturgia/110925-o-deus-de-toda-sabedoria/download">Download</a><br/>
    <Link className="" to="/liturgia/110125-uma-igreja-que-ama-ao-senhor">Uma Igreja que ama ao Senhor - 01 de Novembro de 2025</Link> <a className="" href="/liturgia/110125-uma-igreja-que-ama-ao-senhor/download">Download</a><br/>
    <Link className="" to="/liturgia/102625-a-igreja-que-adora-a-deus-de-forma-verdadeira">A igreja que adora a Deus de forma verdadeira - 26 de Outubro de 2025</Link> <a className="" href="/liturgia/102625-a-igreja-que-adora-a-deus-de-forma-verdadeira/download">Download</a><br/>
    <Link className="" to="/liturgia/101925-seja-fiel-ate-a-morte">Seja Fiel Até a Morte - 19 de Outubro de 2025</Link> <a className="" href="/liturgia/101925-seja-fiel-ate-a-morte/download">Download</a><br/>
    <Link className="" to="/liturgia/101225-jesus-a-palavra-final-de-deus">Jesus, a Palavra Final de Deus - 12 de Outubro de 2025</Link> <a className="" href="/liturgia/101225-jesus-a-palavra-final-de-deus/download">Download</a><br/>
    <Link className="" to="/liturgia/100525-a-igreja-que-recebe-a-novidade-do-evangelho">A igreja que recebe a novidade do evangelho - 05 de Outubro de 2025</Link> <a className="" href="/liturgia/100525-a-igreja-que-recebe-a-novidade-do-evangelho/download">Download</a><br/>
    <Link className="" to="/liturgia/092125-o-deus-que-perdoa-pecados">O Deus que perdoa pecados - 21 de Setembro de 2025</Link> <a className="" href="/liturgia/092125-o-deus-que-perdoa-pecados/download">Download</a><br/>
    <Link className="" to="/liturgia/090725-o-que-o-senhor-espera-do-seu-povo">O Que o Senhor Espera do Seu Povo - 7 de Setembro de 2025</Link> <a className="" href="/liturgia/090725-o-que-o-senhor-espera-do-seu-povo/download">Download</a><br/>
    <Link className="" to="/liturgia/083125-adorando-a-cristo-nosso-rei-pastor-e-juiz">Adorando a Cristo nosso Rei, Pastor e Juíz - 31 de Agosto de 2025</Link> <a className="" href="/liturgia/083125-adorando-a-cristo-nosso-rei-pastor-e-juiz/download">Download</a><br/>
    <Link className="" to="/liturgia/082425-uma-igreja-que-adora-verdadeiramente">Uma igreja que adora verdadeiramente - 24 de Agosto de 2025</Link> <a className="" href="/liturgia/082425-uma-igreja-que-adora-verdadeiramente/download">Download</a><br/>
    <Link className="" to="/liturgia/081725-o-futuro-glorioso-do-povo-de-deus">O Futuro Glorioso do Povo de Deus - 17 de Agosto de 2025</Link> <a className="" href="/liturgia/081725-o-futuro-glorioso-do-povo-de-deus/download">Download</a><br/>
    <Link className="" to="/liturgia/081025-o-povo-sofre-por-lideres-maus">O Povo Sofre Por Líderes Maus - 10 de Agosto de 2025</Link> <a className="" href="/liturgia/081025-o-povo-sofre-por-lideres-maus/download">Download</a><br/>
    <Link className="" to="/liturgia/080325-a-esperanca-vem-do-senhor">A Esperança Vem do Senhor - 03 de Agosto de 2025</Link> <a className="" href="/liturgia/080325-a-esperanca-vem-do-senhor/download">Download</a><br/>
    <Link className="" to="/liturgia/072725-o-juizo-comeca-pela-casa-de-deus">O Juízo Começa Pela Casa de Deus - 27 de Julho de 2025</Link> <a className="" href="/liturgia/072725-o-juizo-comeca-pela-casa-de-deus/download">Download</a><br/>
    <Link className="" to="/liturgia/072025-superando-os-obstaculos-da-evangelizacao">Superando Os Obstáculos Da Evangelização - 20 de Julho de 2025</Link> <a className="" href="/liturgia/072025-superando-os-obstaculos-da-evangelizacao/download">Download</a><br/>
    <Link className="" to="/liturgia/070525-celebrando-ao-senhor-com-gratidao">Celebrando ao Senhor com Gratidão - 5 de Julho de 2025</Link> <a className="" href="/liturgia/070525-celebrando-ao-senhor-com-gratidao/download">Download</a><br/>
    <Link className="" to="/liturgia/062925-uma-igreja-que-ama-a-deus-acima-de-tudo">Uma Igreja que ama a Deus acima de tudo - 29 de Junho de 2025</Link> <a className="" href="/liturgia/062925-uma-igreja-que-ama-a-deus-acima-de-tudo/download">Download</a><br/>
    <Link className="" to="/liturgia/061525-uma-igreja-perseguida">Uma Igreja Perseguida - 15 de Junho de 2025</Link> <a className="" href="/liturgia/061525-uma-igreja-perseguida/download">Download</a><br/>
    <Link className="" to="/liturgia/060825-confiado-no-senhor">Confiado no Senhor - 08 de Junho de 2025</Link> <a className="" href="/liturgia/060825-confiado-no-senhor/download">Download</a><br/>
    <Link className="" to="/liturgias/060125-jesus-o-nosso-pescador-por-excelencia">Jesus, o nosso pescador por excelência - 01 de Junho de 2025</Link> <a className="" href="/liturgia/060125-jesus-o-nosso-pescador-por-excelencia/download">Download</a><br/>
</div>)
}