import { Link } from '@remix-run/react'

export default function Liturgias() {
  return (<div>
    <Link className="" to="/liturgias/010724-o-cordeiro-de-deus">O Cordeiro de Deus - 07 de Janeiro de 2024</Link> <a className="" href="/liturgias/010724-o-cordeiro-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/011424-um-povo-que-segue-jesus-cristo">Um Povo Que Segue Jesus Cristo - 14 de Janeiro de 2024</Link> <a className="" href="/liturgias/011424-um-povo-que-segue-jesus-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/012124-vivendo-sob-a-providencia-de-deus">Vivendo Sob a Providência de Deus - 21 de Janeiro de 2024</Link> <a className="" href="/liturgias/012124-vivendo-sob-a-providencia-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/012824-o-povo-chamado-por-cristo">O Povo Chamado Por Cristo - 28 de Janeiro de 2024</Link> <a className="" href="/liturgias/012824-o-povo-chamado-por-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/020424-contemplando-o-poder-divino">Contemplando O Poder Divino - 4 de Fevereiro de 2024</Link> <a className="" href="/liturgias/020424-contemplando-o-poder-divino/download">Download</a><br />
    <Link className="" to="/liturgias/021124-um-povo-que-adora-ao-senhor">Um Povo Que Adora Ao Senhor - 11 de Fevereiro de 2024</Link> <a className="" href="/liturgias/021124-um-povo-que-adora-ao-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/021824-desafiados-a-progredir-em-fe">Desafiados a progredir em fé - 18 de Fevereiro de 2024</Link> <a className="" href="/liturgias/021824-desafiados-a-progredir-em-fe/download">Download</a><br />
    <Link className="" to="/liturgias/022524-uma-igreja-governada-por-um-justo-rei">Uma igreja governada por um Justo Rei - 25 de Fevereiro de 2024</Link> <a className="" href="/liturgias/022524-uma-igreja-governada-por-um-justo-rei/download">Download</a><br />
    <Link className="" to="/liturgias/031024-salvos-para-uma-viva-esperanca">Salvos para uma viva esperança - 10 de Março de 2024</Link> <a className="" href="/liturgias/031024-salvos-para-uma-viva-esperanca/download">Download</a><br />
    <Link className="" to="/liturgias/031724-santificados-no-amor">Santificados no amor - 17 de Março de 2024</Link> <a className="" href="/liturgias/031724-santificados-no-amor/download">Download</a><br />
    <Link className="" to="/liturgias/032424-o-deus-que-habita-no-meio-do-seu-povo">O Deus que habita no meio do seu povo - 24 de Março de 2024</Link> <a className="" href="/liturgias/032424-o-deus-que-habita-no-meio-do-seu-povo/download">Download</a><br />
    <Link className="" to="/liturgias/033124-a-ressurreicao-de-jesus-cristo">A Ressurreição de Jesus Cristo - 31 de Março de 2024</Link> <a className="" href="/liturgias/033124-a-ressurreicao-de-jesus-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/040724-uma-igreja-firmada-na-misericordia-de-deus">Uma Igreja Firmada na Misericórdia de Deus - 07 de Abril de 2024</Link> <a className="" href="/liturgias/040724-uma-igreja-firmada-na-misericordia-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/041424-uma-igreja-cheia-de-mansidao">Uma Igreja Cheia de Mansidão - 14 de Abril de 2024</Link> <a className="" href="/liturgias/041424-uma-igreja-cheia-de-mansidao/download">Download</a><br />
    <Link className="" to="/liturgias/042124-um-povo-nascido-do-espirito">Um Povo Nascido do Espírito - 21 de Abril de 2024</Link> <a className="" href="/liturgias/042124-um-povo-nascido-do-espirito/download">Download</a><br />
    <Link className="" to="/liturgias/042824-o-amor-de-deus">O Amor de Deus - 28 de Abril de 2024</Link> <a className="" href="/liturgias/042824-o-amor-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/063024-quando-a-igreja-confia-no-senhor">Quando a igreja confia no Senhor - 30 de Junho de 2024</Link> <a className="" href="/liturgias/063024-quando-a-igreja-confia-no-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/070724-uma-igreja-encorajada-no-senhor">Uma igreja encorajada no Senhor - 07 de Julho de 2024</Link> <a className="" href="/liturgias/070724-uma-igreja-encorajada-no-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/072824-cultivando-a-humildade">Cultivando a Humildade - 28 de Julho de 2024</Link> <a className="" href="/liturgias/072824-cultivando-a-humildade/download">Download</a><br />
    <Link className="" to="/liturgias/080424-o-compromisso-missionario-da-igreja">O Compromisso Missionário da Igreja - 04 de Agosto de 2024</Link> <a className="" href="/liturgias/080424-o-compromisso-missionario-da-igreja/download">Download</a><br />
    <Link className="" to="/liturgias/081124-a-igreja-em-adoracao">A Igreja em Adoração - 11 de Agosto de 2024</Link> <a className="" href="/liturgias/081124-a-igreja-em-adoracao/download">Download</a><br />
    <Link className="" to="/liturgias/081824-o-salvador-do-mundo">O Salvador do Mundo - 18 de Agosto de 2024</Link> <a className="" href="/liturgias/081824-o-salvador-do-mundo/download">Download</a><br />
    <Link className="" to="/liturgias/082524-desenvolvemos-a-fe-em-meio-ao-sofrimento">Desenvolvemos a fé em meio ao sofrimento - 25 de Agosto de 2024</Link> <a className="" href="/liturgias/082524-desenvolvemos-a-fe-em-meio-ao-sofrimento/download">Download</a><br />
    <Link className="" to="/liturgias/090124-o-deus-que-nos-encontra-em-nossa-necessidade">O Deus que nos encontra em nossa necessidade - 01 de Setembro de 2024</Link> <a className="" href="/liturgias/090124-o-deus-que-nos-encontra-em-nossa-necessidade/download">Download</a><br />
    <Link className="" to="/liturgias/091524-servindo-uns-aos-outros">Servindo uns aos outros - 15 de Setembro de 2024</Link> <a className="" href="/liturgias/091524-servindo-uns-aos-outros/download">Download</a><br />
    <Link className="" to="/liturgias/092224-quando-a-igreja-confia-no-senhor">Quando a igreja confia no Senhor - 22 de Setembro de 2024</Link> <a className="" href="/liturgias/092224-quando-a-igreja-confia-no-senhor/download">Download</a><br />
  </div>)
}