import { Link } from '@remix-run/react'

export default function Liturgias() {
  return (<div>
    <Link className="" to="/liturgias/010724-o-cordeiro-de-deus">O Cordeiro de Deus - 07 de Janeiro de 2024</Link> <a className="" href="/liturgias/010724-o-cordeiro-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/011424-um-povo-que-segue-jesus-cristo">Um Povo Que Segue Jesus Cristo - 14 de Janeiro de 2024</Link> <a className="" href="/liturgias/011424-um-povo-que-segue-jesus-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/012124-vivendo-sob-a-providencia-de-deus">Vivendo Sob a Providência de Deus - 21 de Janeiro de 2024</Link> <a className="" href="/liturgias/012124-vivendo-sob-a-providencia-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/012824-o-povo-chamado-por-cristo">O Povo Chamado Por Cristo - 28 de Janeiro de 2024</Link> <a className="" href="/liturgias/012824-o-povo-chamado-por-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/020424-contemplando-o-poder-divino">Contemplando O Poder Divino - 4 de Fevereiro de 2024</Link> <a className="" href="/liturgias/020424-contemplando-o-poder-divino/download">Download</a><br />
    <Link className="" to="/liturgias/021124-um-povo-que-adora-ao-senhor">Um Povo Que Adora Ao Senhor - 11 de Fevereiro de 2024</Link> <a className="" href="/liturgias/021124-um-povo-que-adora-ao-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/021824-desafiados-a-progredir-em-fe">Desafiados a progredir em fé - 18 de Fevereiro de 2024</Link> <a className="" href="/liturgias/021824-desafiados-a-progredir-em-fe/download">Download</a><br />
    <Link className="" to="/liturgias/022524-uma-igreja-governada-por-um-justo-rei">Uma igreja governada por um Justo Rei - 25 de Fevereiro de 2024</Link> <a className="" href="/liturgias/022524-uma-igreja-governada-por-um-justo-rei/download">Download</a><br />
    <Link className="" to="/liturgias/031024-salvos-para-uma-viva-esperanca">Salvos para uma viva esperança - 10 de Março de 2024</Link> <a className="" href="/liturgias/031024-salvos-para-uma-viva-esperanca/download">Download</a><br />
    <Link className="" to="/liturgias/031724-santificados-no-amor">Santificados no amor - 17 de Março de 2024</Link> <a className="" href="/liturgias/031724-santificados-no-amor/download">Download</a><br />
    <Link className="" to="/liturgias/032424-o-deus-que-habita-no-meio-do-seu-povo">O Deus que habita no meio do seu povo - 24 de Março de 2024</Link> <a className="" href="/liturgias/032424-o-deus-que-habita-no-meio-do-seu-povo/download">Download</a><br />
    <Link className="" to="/liturgias/033124-a-ressurreicao-de-jesus-cristo">A Ressurreição de Jesus Cristo - 31 de Março de 2024</Link> <a className="" href="/liturgias/033124-a-ressurreicao-de-jesus-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/040724-uma-igreja-firmada-na-misericordia-de-deus">Uma Igreja Firmada na Misericórdia de Deus - 07 de Abril de 2024</Link> <a className="" href="/liturgias/040724-uma-igreja-firmada-na-misericordia-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/041424-uma-igreja-cheia-de-mansidao">Uma Igreja Cheia de Mansidão - 14 de Abril de 2024</Link> <a className="" href="/liturgias/041424-uma-igreja-cheia-de-mansidao/download">Download</a><br />
    <Link className="" to="/liturgias/042124-um-povo-nascido-do-espirito">Um Povo Nascido do Espírito - 21 de Abril de 2024</Link> <a className="" href="/liturgias/042124-um-povo-nascido-do-espirito/download">Download</a><br />
    <Link className="" to="/liturgias/042824-o-amor-de-deus">O Amor de Deus - 28 de Abril de 2024</Link> <a className="" href="/liturgias/042824-o-amor-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/063024-quando-a-igreja-confia-no-senhor">Quando a igreja confia no Senhor - 30 de Junho de 2024</Link> <a className="" href="/liturgias/063024-quando-a-igreja-confia-no-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/070724-uma-igreja-encorajada-no-senhor">Uma igreja encorajada no Senhor - 07 de Julho de 2024</Link> <a className="" href="/liturgias/070724-uma-igreja-encorajada-no-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/072824-cultivando-a-humildade">Cultivando a Humildade - 28 de Julho de 2024</Link> <a className="" href="/liturgias/072824-cultivando-a-humildade/download">Download</a><br />
    <Link className="" to="/liturgias/080424-o-compromisso-missionario-da-igreja">O Compromisso Missionário da Igreja - 04 de Agosto de 2024</Link> <a className="" href="/liturgias/080424-o-compromisso-missionario-da-igreja/download">Download</a><br />
    <Link className="" to="/liturgias/081124-a-igreja-em-adoracao">A Igreja em Adoração - 11 de Agosto de 2024</Link> <a className="" href="/liturgias/081124-a-igreja-em-adoracao/download">Download</a><br />
    <Link className="" to="/liturgias/081824-o-salvador-do-mundo">O Salvador do Mundo - 18 de Agosto de 2024</Link> <a className="" href="/liturgias/081824-o-salvador-do-mundo/download">Download</a><br />
    <Link className="" to="/liturgias/082524-desenvolvemos-a-fe-em-meio-ao-sofrimento">Desenvolvemos a fé em meio ao sofrimento - 25 de Agosto de 2024</Link> <a className="" href="/liturgias/082524-desenvolvemos-a-fe-em-meio-ao-sofrimento/download">Download</a><br />
    <Link className="" to="/liturgias/090124-o-deus-que-nos-encontra-em-nossa-necessidade">O Deus que nos encontra em nossa necessidade - 01 de Setembro de 2024</Link> <a className="" href="/liturgias/090124-o-deus-que-nos-encontra-em-nossa-necessidade/download">Download</a><br />
    <Link className="" to="/liturgias/091524-servindo-uns-aos-outros">Servindo uns aos outros - 15 de Setembro de 2024</Link> <a className="" href="/liturgias/091524-servindo-uns-aos-outros/download">Download</a><br />
    <Link className="" to="/liturgias/092224-quando-a-igreja-confia-no-senhor">Quando a igreja confia no Senhor - 22 de Setembro de 2024</Link> <a className="" href="/liturgias/092224-quando-a-igreja-confia-no-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/092924-uma-igreja-comprometida-a-seu-supremo-pastor-jesus-cristo">Uma igreja comprometida a seu Supremo Pastor, Jesus Cristo - 29 de Setembro de 2024</Link> <a className="" href="/liturgias/092924-uma-igreja-comprometida-a-seu-supremo-pastor-jesus-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/100624-o-salvador-do-mundo">O Salvador do Mundo - 06 de Outubro de 2024</Link> <a className="" href="/liturgias/100624-o-salvador-do-mundo/download">Download</a><br />
    <Link className="" to="/liturgias/101324-a-gloriosa-igreja-triunfante">A Gloriosa Igreja Triunfante - 13 de Outubro de 2024</Link> <a className="" href="/liturgias/101324-a-gloriosa-igreja-triunfante/download">Download</a><br />
    <Link className="" to="/liturgias/102024-igreja-de-cristo-comprometida-com-o-anuncio-do-evangelho">Igreja de Cristo comprometida com o avanço do Evangelho - 20 de Outubro de 2024</Link> <a className="" href="/liturgias/102024-igreja-de-cristo-comprometida-com-o-anuncio-do-evangelho/download">Download</a><br />
    <Link className="" to="/liturgias/102624-santificados-pela-palavra-de-deus">Santificados pela Palavra de Deus - 26 de Outubro de 2024</Link> <a className="" href="/liturgias/102624-santificados-pela-palavra-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/102724-a-autoridade-das-escrituras">A Autoridade das Escrituras - 27 de Outubro de 2024</Link> <a className="" href="/liturgias/102724-a-autoridade-das-escrituras/download">Download</a><br />
    <Link className="" to="/liturgias/110324-vivendo-o-perdao-biblico">Vivendo o perdão bíblico - 03 de Novembro de 2024</Link> <a className="" href="/liturgias/110324-vivendo-o-perdao-biblico/download">Download</a><br />
    <Link className="" to="/liturgias/111024-progredindo-espiritualmente">Progredindo Espiritualmente - 10 de Novembro de 2024</Link> <a className="" href="/liturgias/111024-progredindo-espiritualmente/download">Download</a><br />
    <Link className="" to="/liturgias/111724-uma-igreja-com-o-coracao-centrado-em-deus">Uma Igreja com o coração centrado em Deus - 17 de Novembro de 2024</Link> <a className="" href="/liturgias/111724-uma-igreja-com-o-coracao-centrado-em-deus/download">Download</a><br />
    <Link className="" to="/liturgias/112424-gratos-por-pertencer-a-igreja-de-cristo">Gratos por pertencer à igreja de Cristo - 24 de Novembro de 2024</Link> <a className="" href="/liturgias/112424-gratos-por-pertencer-a-igreja-de-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/120124-a-divindade-de-jesus-cristo">A Divindade de Jesus Cristo - 1 de Dezembro de 2024</Link> <a className="" href="/liturgias/120124-a-divindade-de-jesus-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/120824-jesus-o-poderoso-filho-de-deus">Jesus, O Poderoso Filho de Deus - 8 de Dezembro de 2024</Link> <a className="" href="/liturgias/120824-jesus-o-poderoso-filho-de-deus/download">Download</a><br />
    <Link className="" to="/liturgias/121524-a-alegria-do-natal">A Alegria do Natal - 15 de Dezembro de 2024</Link> <a className="" href="/liturgias/121524-a-alegria-do-natal/download">Download</a><br />
    <Link className="" to="/liturgias/122224-uma-alma-que-engrandece-ao-senhor">Uma alma que engrandece ao Senhor - 22 de Dezembro de 2024</Link> <a className="" href="/liturgias/122224-uma-alma-que-engrandece-ao-senhor/download">Download</a><br />
    <Link className="" to="/liturgias/122924-a-amada-igreja-de-cristo">A amada igreja de Cristo - 29 de Dezembro de 2024</Link> <a className="" href="/liturgias/122924-a-amada-igreja-de-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/010525-a-alegria-na-expansao-do-evangelho">A Alegria Na Expansão Do Evangelho - 05 de Janeiro de 2025</Link> <a className="" href="/liturgias/010525-a-alegria-na-expansao-do-evangelho/download">Download</a><br />
    <Link className="" to="/liturgias/011225-a-alegria-na-expansao-do-evangelho">A Alegria Na Expansão Do Evangelho - 12 de Janeiro de 2025</Link> <a className="" href="/liturgias/011225-a-alegria-na-expansao-do-evangelho/download">Download</a><br />
    <Link className="" to="/liturgias/011925-alegria-em-meio-ao-sofrimento">Alegria em meio ao sofrimento - 19 de Janeiro de 2025</Link> <a className="" href="/liturgias/011925-alegria-em-meio-ao-sofrimento/download">Download</a><br />
    <Link className="" to="/liturgias/012625-a-alegria-de-servir-a-cristo">A Alegria de Servir a Cristo - 26 de Janeiro de 2025</Link> <a className="" href="/liturgias/012625-a-alegria-de-servir-a-cristo/download">Download</a><br />
    <Link className="" to="/liturgias/020225-vivendo-como-cidadao-do-ceu">Vivendo como cidadão do Ceu - 2 de Fevereiro de 2025</Link> <a className="" href="/liturgias/020225-vivendo-como-cidadao-do-ceu/download">Download</a><br />
  </div>)
}